services:
  web:
    build:
     context: ./
     dockerfile: "test/docker/php/Dockerfile"
    ports:
      - "90:80"
  web_dev:
    build:
      context: ./
      dockerfile: "test/docker/php/Dockerfile_dev"
    volumes:
      - "./:/var/php/"
    ports:
      - "91:80"